# DATABASE
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://db:5432/weather_tracker_db
db.username=postgres
db.password=postgres.Ilias

# HIBERNATE
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

# weather api
weather.api.key=b177eda7fb885795cd3fa2ad93b3c324